// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"eats/backend/common"
	"eats/backend/common/shared"
	"eats/backend/orders/app"
	"github.com/shopspring/decimal"
)

type OrdersCustomer struct {
	CustomerUuid app.CustomerUUID
	Name         string
	Email        string
	Address      shared.Address
	PhoneNumber  string
}

type OrdersRestaurant struct {
	RestaurantUuid common.UUID
	Name           string
	Description    string
	Address        []byte
	Currency       string
}

type OrdersRestaurantMenuItem struct {
	RestaurantMenuItemUuid common.UUID
	RestaurantUuid         common.UUID
	Name                   string
	GrossPrice             decimal.Decimal
	Ordering               float64
	IsArchived             bool
}
