// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package dbmodels

import (
	"context"
	"time"

	"eats/backend/common"
	"eats/backend/common/shared"
	"eats/backend/orders/app"
	"github.com/shopspring/decimal"
)

const addQuote = `-- name: AddQuote :exec
INSERT INTO orders.quotes (
	quote_uuid,
	customer_uuid,
	restaurant_uuid,
	delivery_address,
	items_subtotal_gross,
	service_fee_gross,
	delivery_fee_gross,
	total_amount_gross,
	total_tax,
	created_at,
	currency
)
VALUES
	($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type AddQuoteParams struct {
	QuoteUuid          app.QuoteUUID
	CustomerUuid       app.CustomerUUID
	RestaurantUuid     app.RestaurantUUID
	DeliveryAddress    shared.Address
	ItemsSubtotalGross decimal.Decimal
	ServiceFeeGross    decimal.Decimal
	DeliveryFeeGross   decimal.Decimal
	TotalAmountGross   decimal.Decimal
	TotalTax           decimal.Decimal
	CreatedAt          time.Time
	Currency           shared.Currency
}

// Quotes are immutable - no update query exists. If needed, create a new quote.
func (q *Queries) AddQuote(ctx context.Context, arg AddQuoteParams) error {
	_, err := q.db.Exec(ctx, addQuote,
		arg.QuoteUuid,
		arg.CustomerUuid,
		arg.RestaurantUuid,
		arg.DeliveryAddress,
		arg.ItemsSubtotalGross,
		arg.ServiceFeeGross,
		arg.DeliveryFeeGross,
		arg.TotalAmountGross,
		arg.TotalTax,
		arg.CreatedAt,
		arg.Currency,
	)
	return err
}

type AddQuoteItemsParams struct {
	QuoteItemUuid common.UUID
	QuoteUuid     app.QuoteUUID
	MenuItemUuid  app.RestaurantMenuItemUUID
	GrossPrice    decimal.Decimal
	Quantity      int32
}

const getMenuItemsForQuote = `-- name: GetMenuItemsForQuote :many
SELECT
	mi.restaurant_menu_item_uuid, mi.restaurant_uuid, mi.name, mi.gross_price, mi.ordering, mi.is_archived
FROM orders.quote_items AS qi
INNER JOIN  orders.restaurant_menu_items AS mi ON mi.restaurant_menu_item_uuid = qi.menu_item_uuid
WHERE qi.quote_uuid = $1
`

func (q *Queries) GetMenuItemsForQuote(ctx context.Context, quoteUuid app.QuoteUUID) ([]OrdersRestaurantMenuItem, error) {
	rows, err := q.db.Query(ctx, getMenuItemsForQuote, quoteUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersRestaurantMenuItem{}
	for rows.Next() {
		var i OrdersRestaurantMenuItem
		if err := rows.Scan(
			&i.RestaurantMenuItemUuid,
			&i.RestaurantUuid,
			&i.Name,
			&i.GrossPrice,
			&i.Ordering,
			&i.IsArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuote = `-- name: GetQuote :one
SELECT
	quote_uuid, customer_uuid, restaurant_uuid, delivery_address, created_at, items_subtotal_gross, service_fee_gross, delivery_fee_gross, total_amount_gross, total_tax, currency
FROM
	orders.quotes AS quotes
WHERE
	quote_uuid = $1
LIMIT 1
`

func (q *Queries) GetQuote(ctx context.Context, quoteUuid app.QuoteUUID) (OrdersQuote, error) {
	row := q.db.QueryRow(ctx, getQuote, quoteUuid)
	var i OrdersQuote
	err := row.Scan(
		&i.QuoteUuid,
		&i.CustomerUuid,
		&i.RestaurantUuid,
		&i.DeliveryAddress,
		&i.CreatedAt,
		&i.ItemsSubtotalGross,
		&i.ServiceFeeGross,
		&i.DeliveryFeeGross,
		&i.TotalAmountGross,
		&i.TotalTax,
		&i.Currency,
	)
	return i, err
}

const getQuoteItems = `-- name: GetQuoteItems :many
SELECT quote_item_uuid, quote_uuid, menu_item_uuid, gross_price, quantity
FROM orders.quote_items
WHERE quote_uuid = $1
`

func (q *Queries) GetQuoteItems(ctx context.Context, quoteUuid app.QuoteUUID) ([]OrdersQuoteItem, error) {
	rows, err := q.db.Query(ctx, getQuoteItems, quoteUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersQuoteItem{}
	for rows.Next() {
		var i OrdersQuoteItem
		if err := rows.Scan(
			&i.QuoteItemUuid,
			&i.QuoteUuid,
			&i.MenuItemUuid,
			&i.GrossPrice,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO orders.orders (
	order_uuid,
	quote_uuid,
	customer_uuid,
	restaurant_uuid,
	delivery_address,
	ordered_at,
	items_subtotal_gross,
	service_fee_gross,
	delivery_fee_gross,
	total_amount_gross,
	total_tax,
	courier_uuid,
	currency
)
VALUES
	($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING order_uuid, quote_uuid, customer_uuid, restaurant_uuid, courier_uuid, delivery_address, ordered_at, restaurant_confirmed_at, courier_accepted_at, restaurant_prepared_at, picked_up_at, delivered_at, items_subtotal_gross, service_fee_gross, delivery_fee_gross, total_amount_gross, total_tax, currency
`

type InsertOrderParams struct {
	OrderUuid          app.OrderUUID
	QuoteUuid          app.QuoteUUID
	CustomerUuid       app.CustomerUUID
	RestaurantUuid     app.RestaurantUUID
	DeliveryAddress    shared.Address
	OrderedAt          time.Time
	ItemsSubtotalGross decimal.Decimal
	ServiceFeeGross    decimal.Decimal
	DeliveryFeeGross   decimal.Decimal
	TotalAmountGross   decimal.Decimal
	TotalTax           decimal.Decimal
	CourierUuid        *app.CourierUUID
	Currency           shared.Currency
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder,
		arg.OrderUuid,
		arg.QuoteUuid,
		arg.CustomerUuid,
		arg.RestaurantUuid,
		arg.DeliveryAddress,
		arg.OrderedAt,
		arg.ItemsSubtotalGross,
		arg.ServiceFeeGross,
		arg.DeliveryFeeGross,
		arg.TotalAmountGross,
		arg.TotalTax,
		arg.CourierUuid,
		arg.Currency,
	)
	return err
}
