// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read_models.sql

package dbmodels

import (
	"context"
	"time"

	"eats/backend/common/shared"
	"eats/backend/orders/app"
	"github.com/shopspring/decimal"
)

const listAssignedCourierOrders = `-- name: ListAssignedCourierOrders :many
SELECT orders.order_uuid, orders.quote_uuid, orders.customer_uuid, orders.restaurant_uuid, orders.courier_uuid, orders.delivery_address, orders.ordered_at, orders.restaurant_confirmed_at, orders.courier_accepted_at, orders.restaurant_prepared_at, orders.picked_up_at, orders.delivered_at, orders.items_subtotal_gross, orders.service_fee_gross, orders.delivery_fee_gross, orders.total_amount_gross, orders.total_tax, orders.currency, restaurants.name AS restaurant_name FROM orders.orders as orders
INNER JOIN orders.restaurants ON orders.restaurant_uuid = restaurants.restaurant_uuid
WHERE courier_uuid = $1
`

type ListAssignedCourierOrdersRow struct {
	OrderUuid             app.OrderUUID
	QuoteUuid             app.QuoteUUID
	CustomerUuid          app.CustomerUUID
	RestaurantUuid        app.RestaurantUUID
	CourierUuid           *app.CourierUUID
	DeliveryAddress       shared.Address
	OrderedAt             time.Time
	RestaurantConfirmedAt *time.Time
	CourierAcceptedAt     *time.Time
	RestaurantPreparedAt  *time.Time
	PickedUpAt            *time.Time
	DeliveredAt           *time.Time
	ItemsSubtotalGross    decimal.Decimal
	ServiceFeeGross       decimal.Decimal
	DeliveryFeeGross      decimal.Decimal
	TotalAmountGross      decimal.Decimal
	TotalTax              decimal.Decimal
	Currency              shared.Currency
	RestaurantName        string
}

func (q *Queries) ListAssignedCourierOrders(ctx context.Context, courierUuid *app.CourierUUID) ([]ListAssignedCourierOrdersRow, error) {
	rows, err := q.db.Query(ctx, listAssignedCourierOrders, courierUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignedCourierOrdersRow{}
	for rows.Next() {
		var i ListAssignedCourierOrdersRow
		if err := rows.Scan(
			&i.OrderUuid,
			&i.QuoteUuid,
			&i.CustomerUuid,
			&i.RestaurantUuid,
			&i.CourierUuid,
			&i.DeliveryAddress,
			&i.OrderedAt,
			&i.RestaurantConfirmedAt,
			&i.CourierAcceptedAt,
			&i.RestaurantPreparedAt,
			&i.PickedUpAt,
			&i.DeliveredAt,
			&i.ItemsSubtotalGross,
			&i.ServiceFeeGross,
			&i.DeliveryFeeGross,
			&i.TotalAmountGross,
			&i.TotalTax,
			&i.Currency,
			&i.RestaurantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableOrdersForCourier = `-- name: ListAvailableOrdersForCourier :many
SELECT orders.order_uuid, orders.quote_uuid, orders.customer_uuid, orders.restaurant_uuid, orders.courier_uuid, orders.delivery_address, orders.ordered_at, orders.restaurant_confirmed_at, orders.courier_accepted_at, orders.restaurant_prepared_at, orders.picked_up_at, orders.delivered_at, orders.items_subtotal_gross, orders.service_fee_gross, orders.delivery_fee_gross, orders.total_amount_gross, orders.total_tax, orders.currency , restaurants.name AS restaurant_name
FROM orders.orders as orders
INNER JOIN orders.couriers ON couriers.courier_uuid = $1
INNER JOIN orders.restaurants ON orders.restaurant_uuid = restaurants.restaurant_uuid
WHERE orders.restaurant_confirmed_at IS NOT NULL
AND orders.courier_uuid IS NULL
AND orders.delivered_at IS NULL
AND orders.courier_accepted_at IS NULL

AND couriers.city = orders.delivery_address ->> 'city'
`

type ListAvailableOrdersForCourierRow struct {
	OrderUuid             app.OrderUUID
	QuoteUuid             app.QuoteUUID
	CustomerUuid          app.CustomerUUID
	RestaurantUuid        app.RestaurantUUID
	CourierUuid           *app.CourierUUID
	DeliveryAddress       shared.Address
	OrderedAt             time.Time
	RestaurantConfirmedAt *time.Time
	CourierAcceptedAt     *time.Time
	RestaurantPreparedAt  *time.Time
	PickedUpAt            *time.Time
	DeliveredAt           *time.Time
	ItemsSubtotalGross    decimal.Decimal
	ServiceFeeGross       decimal.Decimal
	DeliveryFeeGross      decimal.Decimal
	TotalAmountGross      decimal.Decimal
	TotalTax              decimal.Decimal
	Currency              shared.Currency
	RestaurantName        string
}

func (q *Queries) ListAvailableOrdersForCourier(ctx context.Context, courierUuid app.CourierUUID) ([]ListAvailableOrdersForCourierRow, error) {
	rows, err := q.db.Query(ctx, listAvailableOrdersForCourier, courierUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableOrdersForCourierRow{}
	for rows.Next() {
		var i ListAvailableOrdersForCourierRow
		if err := rows.Scan(
			&i.OrderUuid,
			&i.QuoteUuid,
			&i.CustomerUuid,
			&i.RestaurantUuid,
			&i.CourierUuid,
			&i.DeliveryAddress,
			&i.OrderedAt,
			&i.RestaurantConfirmedAt,
			&i.CourierAcceptedAt,
			&i.RestaurantPreparedAt,
			&i.PickedUpAt,
			&i.DeliveredAt,
			&i.ItemsSubtotalGross,
			&i.ServiceFeeGross,
			&i.DeliveryFeeGross,
			&i.TotalAmountGross,
			&i.TotalTax,
			&i.Currency,
			&i.RestaurantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerOrders = `-- name: ListCustomerOrders :many
SELECT orders.order_uuid, orders.quote_uuid, orders.customer_uuid, orders.restaurant_uuid, orders.courier_uuid, orders.delivery_address, orders.ordered_at, orders.restaurant_confirmed_at, orders.courier_accepted_at, orders.restaurant_prepared_at, orders.picked_up_at, orders.delivered_at, orders.items_subtotal_gross, orders.service_fee_gross, orders.delivery_fee_gross, orders.total_amount_gross, orders.total_tax, orders.currency FROM orders.orders as orders
WHERE customer_uuid = $1
ORDER BY orders.ordered_at DESC
`

func (q *Queries) ListCustomerOrders(ctx context.Context, customerUuid app.CustomerUUID) ([]OrdersOrder, error) {
	rows, err := q.db.Query(ctx, listCustomerOrders, customerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersOrder{}
	for rows.Next() {
		var i OrdersOrder
		if err := rows.Scan(
			&i.OrderUuid,
			&i.QuoteUuid,
			&i.CustomerUuid,
			&i.RestaurantUuid,
			&i.CourierUuid,
			&i.DeliveryAddress,
			&i.OrderedAt,
			&i.RestaurantConfirmedAt,
			&i.CourierAcceptedAt,
			&i.RestaurantPreparedAt,
			&i.PickedUpAt,
			&i.DeliveredAt,
			&i.ItemsSubtotalGross,
			&i.ServiceFeeGross,
			&i.DeliveryFeeGross,
			&i.TotalAmountGross,
			&i.TotalTax,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsWithRestaurant = `-- name: ListMenuItemsWithRestaurant :many
SELECT
    mi.restaurant_menu_item_uuid AS menu_item_uuid,
    mi.name AS menu_item_name,
    mi.gross_price,
    r.currency,
    r.restaurant_uuid,
    r.name AS restaurant_name,
    CASE WHEN $1::text IS NOT NULL
         THEN ts_rank(
             to_tsvector('english', mi.name),
             plainto_tsquery('english', $1::text)
         )
         ELSE NULL
    END AS relevance
FROM orders.restaurant_menu_items mi
JOIN orders.restaurants r ON mi.restaurant_uuid = r.restaurant_uuid
WHERE mi.is_archived = false
  AND ($1::text IS NULL
       OR to_tsvector('english', mi.name) @@ plainto_tsquery('english', $1::text))
  AND ($2::text IS NULL
       OR LOWER(r.name) LIKE LOWER('%' || $2::text || '%'))
ORDER BY
    CASE WHEN $3::text = 'relevance'
         THEN ts_rank(
             to_tsvector('english', mi.name),
             plainto_tsquery('english', $1::text)
         )
    END DESC,
    CASE WHEN ($3::text IS NULL OR $3::text = 'default')
         THEN r.name END ASC,
    CASE WHEN ($3::text IS NULL OR $3::text = 'default')
         THEN mi.ordering END ASC,
    CASE WHEN $3::text = 'price_asc' THEN mi.gross_price END ASC,
    CASE WHEN $3::text = 'price_desc' THEN mi.gross_price END DESC,
    CASE WHEN $3::text = 'name_asc' THEN mi.name END ASC,
    CASE WHEN $3::text = 'name_desc' THEN mi.name END DESC
`

type ListMenuItemsWithRestaurantParams struct {
	SearchTerm           *string
	RestaurantNameFilter *string
	OrderBy              *string
}

type ListMenuItemsWithRestaurantRow struct {
	MenuItemUuid   app.RestaurantMenuItemUUID
	MenuItemName   string
	GrossPrice     decimal.Decimal
	Currency       shared.Currency
	RestaurantUuid app.RestaurantUUID
	RestaurantName string
	Relevance      interface{}
}

// Lists menu items with optional restaurant name filter, optional full-text search, and dynamic ordering.
// Uses CASE WHEN to support multiple ordering options in a single query.
func (q *Queries) ListMenuItemsWithRestaurant(ctx context.Context, arg ListMenuItemsWithRestaurantParams) ([]ListMenuItemsWithRestaurantRow, error) {
	rows, err := q.db.Query(ctx, listMenuItemsWithRestaurant, arg.SearchTerm, arg.RestaurantNameFilter, arg.OrderBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMenuItemsWithRestaurantRow{}
	for rows.Next() {
		var i ListMenuItemsWithRestaurantRow
		if err := rows.Scan(
			&i.MenuItemUuid,
			&i.MenuItemName,
			&i.GrossPrice,
			&i.Currency,
			&i.RestaurantUuid,
			&i.RestaurantName,
			&i.Relevance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestaurantOrders = `-- name: ListRestaurantOrders :many
SELECT orders.order_uuid, orders.quote_uuid, orders.customer_uuid, orders.restaurant_uuid, orders.courier_uuid, orders.delivery_address, orders.ordered_at, orders.restaurant_confirmed_at, orders.courier_accepted_at, orders.restaurant_prepared_at, orders.picked_up_at, orders.delivered_at, orders.items_subtotal_gross, orders.service_fee_gross, orders.delivery_fee_gross, orders.total_amount_gross, orders.total_tax, orders.currency FROM orders.orders as orders
WHERE restaurant_uuid = $1
`

func (q *Queries) ListRestaurantOrders(ctx context.Context, restaurantUuid app.RestaurantUUID) ([]OrdersOrder, error) {
	rows, err := q.db.Query(ctx, listRestaurantOrders, restaurantUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersOrder{}
	for rows.Next() {
		var i OrdersOrder
		if err := rows.Scan(
			&i.OrderUuid,
			&i.QuoteUuid,
			&i.CustomerUuid,
			&i.RestaurantUuid,
			&i.CourierUuid,
			&i.DeliveryAddress,
			&i.OrderedAt,
			&i.RestaurantConfirmedAt,
			&i.CourierAcceptedAt,
			&i.RestaurantPreparedAt,
			&i.PickedUpAt,
			&i.DeliveredAt,
			&i.ItemsSubtotalGross,
			&i.ServiceFeeGross,
			&i.DeliveryFeeGross,
			&i.TotalAmountGross,
			&i.TotalTax,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestaurants = `-- name: ListRestaurants :many
SELECT
    restaurant_uuid,
    name,
    description,
    address,
    currency
FROM orders.restaurants
ORDER BY name ASC
`

func (q *Queries) ListRestaurants(ctx context.Context) ([]OrdersRestaurant, error) {
	rows, err := q.db.Query(ctx, listRestaurants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersRestaurant{}
	for rows.Next() {
		var i OrdersRestaurant
		if err := rows.Scan(
			&i.RestaurantUuid,
			&i.Name,
			&i.Description,
			&i.Address,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
