// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restaurants.sql

package dbmodels

import (
	"context"

	"eats/backend/common"

	"github.com/shopspring/decimal"
)

const getRestaurant = `-- name: GetRestaurant :one
SELECT
	restaurant_uuid, name, description, address, currency
FROM
	orders.restaurants
WHERE
	restaurant_uuid = $1
`

func (q *Queries) GetRestaurant(ctx context.Context, restaurantUuid common.UUID) (OrdersRestaurant, error) {
	row := q.db.QueryRow(ctx, getRestaurant, restaurantUuid)
	var i OrdersRestaurant
	err := row.Scan(
		&i.RestaurantUuid,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.Currency,
	)
	return i, err
}

const getRestaurantMenu = `-- name: GetRestaurantMenu :many
SELECT r.restaurant_menu_item_uuid, r.restaurant_uuid, r.name, r.gross_price, r.ordering, r.is_archived 
FROM orders.restaurant_menu_items r
WHERE is_archived = FALSE
AND restaurant_uuid = $1
ORDER BY ordering ASC
`

type GetRestaurantMenuRow struct {
	OrdersRestaurantMenuItem OrdersRestaurantMenuItem
}

func (q *Queries) GetRestaurantMenu(ctx context.Context, restaurantUuid common.UUID) ([]GetRestaurantMenuRow, error) {
	rows, err := q.db.Query(ctx, getRestaurantMenu, restaurantUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRestaurantMenuRow{}
	for rows.Next() {
		var i GetRestaurantMenuRow
		if err := rows.Scan(
			&i.OrdersRestaurantMenuItem.RestaurantMenuItemUuid,
			&i.OrdersRestaurantMenuItem.RestaurantUuid,
			&i.OrdersRestaurantMenuItem.Name,
			&i.OrdersRestaurantMenuItem.GrossPrice,
			&i.OrdersRestaurantMenuItem.Ordering,
			&i.OrdersRestaurantMenuItem.IsArchived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRestaurant = `-- name: UpsertRestaurant :one
INSERT INTO orders.restaurants (restaurant_uuid, name, description, address, currency)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (restaurant_uuid) DO UPDATE
SET name = EXCLUDED.name,	
	description = EXCLUDED.description,
	address = EXCLUDED.address,
	currency = EXCLUDED.currency
RETURNING restaurant_uuid, name, description, address, currency
`

type UpsertRestaurantParams struct {
	RestaurantUuid common.UUID
	Name           string
	Description    string
	Address        []byte
	Currency       string
}

func (q *Queries) UpsertRestaurant(ctx context.Context, arg UpsertRestaurantParams) (OrdersRestaurant, error) {
	row := q.db.QueryRow(ctx, upsertRestaurant,
		arg.RestaurantUuid,
		arg.Name,
		arg.Description,
		arg.Address,
		arg.Currency,
	)
	var i OrdersRestaurant
	err := row.Scan(
		&i.RestaurantUuid,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.Currency,
	)
	return i, err
}

const upsertRestaurantMenuItem = `-- name: UpsertRestaurantMenuItem :one
INSERT INTO orders.restaurant_menu_items (restaurant_menu_item_uuid, restaurant_uuid, name, gross_price, ordering, is_archived)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (restaurant_menu_item_uuid) DO UPDATE
SET restaurant_uuid = EXCLUDED.restaurant_uuid,
	name = EXCLUDED.name,
	gross_price = EXCLUDED.gross_price,
	ordering = EXCLUDED.ordering,
	is_archived = EXCLUDED.is_archived
RETURNING restaurant_menu_item_uuid, restaurant_uuid, name, gross_price, ordering, is_archived
`

type UpsertRestaurantMenuItemParams struct {
	RestaurantMenuItemUuid common.UUID
	RestaurantUuid         common.UUID
	Name                   string
	GrossPrice             decimal.Decimal
	Ordering               float64
	IsArchived             bool
}

func (q *Queries) UpsertRestaurantMenuItem(ctx context.Context, arg UpsertRestaurantMenuItemParams) (OrdersRestaurantMenuItem, error) {
	row := q.db.QueryRow(ctx, upsertRestaurantMenuItem,
		arg.RestaurantMenuItemUuid,
		arg.RestaurantUuid,
		arg.Name,
		arg.GrossPrice,
		arg.Ordering,
		arg.IsArchived,
	)
	var i OrdersRestaurantMenuItem
	err := row.Scan(
		&i.RestaurantMenuItemUuid,
		&i.RestaurantUuid,
		&i.Name,
		&i.GrossPrice,
		&i.Ordering,
		&i.IsArchived,
	)
	return i, err
}
